"""Company display names generated before the title-casing fix.

The universe sync creates ``display_name`` once and never rewrites it on an existing
row (it is curated data, see ``src/db/repositories/reference.py``). Rows created
before aa89371 therefore kept names from the old casing rules: a dotless ``ı`` in
ASCII foreign words (Graınturk, Granıte) and title-cased abbreviations (Cvk, Cw,
Mlp, Gmyo, Şok, Tr). Today's generator (``display_name_for``) writes the names
below. A row changes only while it still holds the old generated name, so a name
curated since then stays; the alias holding that name follows it.

Revision ID: 021
Revises: 020
"""

import sqlalchemy as sa
from alembic import op

revision = "021"
down_revision = "020"
branch_labels = None
depends_on = None

# (ticker, generated by the old rules, generated today)
FIXES: tuple[tuple[str, str, str], ...] = (
    ("CVKMD", "Cvk Maden", "CVK Maden"),
    ("CWENE", "Cw Enerji", "CW Enerji"),
    ("GRTHO", "Graınturk Holding", "Grainturk Holding"),
    ("MPARK", "Mlp Sağlık", "MLP Sağlık"),
    ("PSGYO", "Pasifik Gmyo", "Pasifik GMYO"),
    ("QUAGR", "Qua Granıte Hayal Yapı", "Qua Granite Hayal Yapı"),
    ("SOKM", "Şok Marketler Ticaret", "ŞOK Marketler Ticaret"),
    ("TRENJ", "Tr Doğal Enerji", "TR Doğal Enerji"),
    ("TRMET", "Tr Anadolu Metal Madencilik", "TR Anadolu Metal Madencilik"),
)

_RENAME = sa.text(
    """
    UPDATE companies
    SET display_name = :new,
        aliases = CASE
            WHEN jsonb_typeof(aliases) = 'array' THEN (
                SELECT COALESCE(
                    jsonb_agg(CASE WHEN alias = to_jsonb(CAST(:old AS text)) THEN to_jsonb(CAST(:new AS text)) ELSE alias END
                              ORDER BY position),
                    '[]'::jsonb
                )
                FROM jsonb_array_elements(aliases) WITH ORDINALITY AS item(alias, position)
            )
            ELSE aliases
        END
    WHERE ticker = :ticker AND display_name = :old
    """
)


def upgrade() -> None:
    for ticker, old, new in FIXES:
        op.execute(_RENAME.bindparams(ticker=ticker, old=old, new=new))


def downgrade() -> None:
    for ticker, old, new in FIXES:
        op.execute(_RENAME.bindparams(ticker=ticker, old=new, new=old))
