"""add category to normalized_events

Revision ID: b68da92264cf
Revises: 9517464de7c8
Create Date: 2026-03-20 14:33:59.028673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68da92264cf'
down_revision: Union[str, None] = '9517464de7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    event_category = sa.Enum('DIVIDEND', 'CAPITAL_INCREASE', 'NEW_BUSINESS', 'LEGAL', 'MANAGEMENT', 'FINANCIAL_RESULTS', 'OTHER', name='eventcategory')
    event_category.create(op.get_bind(), checkfirst=True)
    op.add_column('normalized_events', sa.Column('category', event_category, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('normalized_events', 'category')
    # ### end Alembic commands ###
