"""Refresh the Turkish names of TradingView economic-calendar events from doviz.com.

TradingView (the calendar's source) publishes English names only; doviz.com (the previous
source) prints Turkish ones for the same releases but only for the current month. This
script pairs the two sources' events for that month (see
``src.adapters.economic_calendar_titles.pair_titles``) and merges the pairs into
``src/adapters/economic_calendar_titles_data.py``: new names are added, names seen again
are refreshed, names not in this month are kept — so every run grows the dictionary.

    .venv/bin/python -m scripts.harvest_calendar_titles           # write the data module
    .venv/bin/python -m scripts.harvest_calendar_titles --dry-run # only print the changes

Run it once a month or so; quarterly releases (GDP, current account) only appear then.
"""

from __future__ import annotations

import argparse
import asyncio
import pprint
from datetime import date, datetime
from pathlib import Path

from src.adapters import economic_calendar as cal
from src.adapters import economic_calendar_titles as titles
from src.adapters.economic_calendar_titles_data import IMPORTANCE, TITLES

DATA_MODULE = Path(__file__).resolve().parent.parent / "src" / "adapters" / "economic_calendar_titles_data.py"


def _render(titles_map: dict[str, str], importance_map: dict[str, str], note: str) -> str:
    def literal(mapping: dict[str, str]) -> str:
        return pprint.pformat(dict(sorted(mapping.items())), width=120, sort_dicts=False)

    return (
        '"""Generated by scripts/harvest_calendar_titles.py — do not edit by hand.\n\n'
        f"{note}\n"
        '"""\n\n'
        "# TradingView (English) event name → the Turkish name doviz.com prints for it.\n"
        f"TITLES: dict[str, str] = {literal(titles_map)}\n\n"
        "# \"<country>|<English name>\" → doviz.com's importance (low / mid / high).\n"
        f"IMPORTANCE: dict[str, str] = {literal(importance_map)}\n"
    )


async def _collect() -> tuple[list[titles.TitlePair], date, date]:
    codes = list(cal.CALENDAR_COUNTRIES)
    fetched, failed = await cal._fetch_countries(codes)
    if failed:
        print(f"doviz.com: no data for {', '.join(failed)}")
    rows = [row for code in codes if code in fetched for row in fetched[code]["rows"]]
    if not rows:
        raise SystemExit("doviz.com returned nothing; nothing to harvest")
    start = min(date.fromisoformat(row["Date"]) for row in rows)
    end = max(date.fromisoformat(row["Date"]) for row in rows)
    events: list[dict] = []
    for month in cal.months_between(start, end):
        events.extend(await cal.fetch_tradingview_month(month))
    return titles.pair_titles(rows, events), start, end


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dry-run", action="store_true", help="print what would change, write nothing")
    args = parser.parse_args()

    pairs, start, end = asyncio.run(_collect())
    new_titles, new_importance = titles.harvest(pairs)
    added = sorted(set(new_titles) - set(TITLES))
    changed = sorted(key for key in new_titles if key in TITLES and TITLES[key] != new_titles[key])
    guessed = sorted({pair.title_en for pair in pairs if not pair.by_value} & set(added))

    print(f"{len(pairs)} pairs ({sum(p.by_value for p in pairs)} by value) from {start} – {end}")
    print(f"titles: {len(TITLES)} known, {len(added)} new, {len(changed)} changed")
    for key in changed:
        print(f"  ~ {key}: {TITLES[key]!r} → {new_titles[key]!r}")
    for key in guessed:
        print(f"  ? {key} → {new_titles[key]!r} (same-slot pair, check it)")
    if args.dry_run:
        for key in added:
            print(f"  + {key} → {new_titles[key]!r}")
        return

    note = (
        f"Last harvest: {datetime.now(cal.ISTANBUL_TZ):%Y-%m-%d %H:%M} (Istanbul), "
        f"doviz.com {start} – {end}, {len(pairs)} paired releases."
    )
    DATA_MODULE.write_text(
        _render({**TITLES, **new_titles}, {**IMPORTANCE, **new_importance}, note), encoding="utf-8"
    )
    print(f"wrote {DATA_MODULE.relative_to(Path.cwd()) if DATA_MODULE.is_relative_to(Path.cwd()) else DATA_MODULE}")


if __name__ == "__main__":
    main()
